logging:
  level:
    org.springframework.security: trace
    org.springframework.cloud.gateway: trace


spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

server:
  port: 8080

app:
  services:
    mandates:
      url: ${MANDATES_SERVICE_URL:http://localhost:8081}
  cors:
    allowed-origins: http://localhost:3000,http://localhost:4200
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type
    max-age: 3600