spring:
  application:
    name: resource
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:9000}
upi:
  auto-pay:
    base-uri: ${UPI_AUTO_PAY_BASE_URI}
    mandate:
      create: ${UPI_AUTO_PAY_MANDATE_CREATE}